//
// Created by nnstein on 22/10/18.
//

#ifndef HASHTABLE_THESIS_ENUMS_H
#define HASHTABLE_THESIS_ENUMS_H

#define SUCCESS 0

#define KEY_NOT_FOUND -1
#define KEY_ALREADY_EXISTS -2
#define INVALID_ARGS -3
#define UNDEFINED_FAILURE -100

#endif //HASHTABLE_THESIS_ENUMS_H
